[package]
name = "object_store"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdb@service.alipay.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.53"
bytes = "1.0"
futures = "0.3"
upstream = { package = "object_store", version =  "0.1.0" }
oss-rust-sdk = "0.4.0"
snafu = { version = "0.6.10", features = ["backtraces"] }
lru = "0.7.6"
chrono = "0.4.19"

[dev-dependencies]
tempfile = "3.1.0"
tokio = { version = "1.0", features = ["full"] }
